import { AppRegistry } from "react-native";

import { name as appName } from "./app.json";
import App from "./src/App";

// Standard bare React Native CLI entry point. The registered component name must
// match `getMainComponentName()` in the native projects (Android `MainActivity`,
// iOS `AppDelegate`) generated by `@react-native-community/cli init`.
AppRegistry.registerComponent(appName, () => App);
